name: Linux Platform Workflow

on:
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:    
  verify-version:
    runs-on: ubuntu-latest
    outputs:
      FASTIN_VERSION: ${{ steps.version.outputs.FASTIN_VERSION }}
    steps:
      - uses: actions/checkout@v4
      - name: Verify version
        id: version
        run: |
          DEFINE_VERSION=$(cat src/main.cpp | grep "define FASTIN_VERSION")
          FASTIN_VERSION=v$(echo $DEFINE_VERSION | grep "[0-9].[0-9].[0-9]" -o)-linux
          if [[ -n "$(git ls-remote origin refs/tags/$FASTIN_VERSION)" ]]; then
            echo Tag "$FASTIN_VERSION" already exists in repository. Make another merge changing the version
            exit 1
          else
            echo Tag "$FASTIN_VERSION" is valid.
            echo "FASTIN_VERSION=v$(echo $DEFINE_VERSION | grep "[0-9].[0-9].[0-9]" -o)" >> "$GITHUB_OUTPUT"
            exit 0
          fi

  build:
    needs: [verify-version]
    env:
      FASTIN_VERSION: ${{ needs.verify-version.outputs.FASTIN_VERSION }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get Dependencies
      run: |
        cd $HOME
        mkdir libraries
        cd libraries
        git clone --branch=v1.x https://github.com/gabime/spdlog.git
        git clone --branch=master https://github.com/zeux/pugixml.git
        git clone --branch=master https://github.com/nlohmann/json.git
        git clone --branch=main https://github.com/CLIUtils/CLI11.git
        git clone --branch=master https://github.com/jbeder/yaml-cpp.git

    - name: Build spdlog dependency
      run: |
        cd $HOME
        cd libraries/spdlog
        mkdir build
        cd build
        cmake .. && cmake --build . --config ${{env.BUILD_TYPE}}
        cd ../../

    - name: Build pugixml dependency
      run: |
        cd $HOME
        cd libraries/pugixml
        mkdir build
        cd build
        cmake .. && cmake --build . --config ${{env.BUILD_TYPE}}
    
    - name: Build yaml-cpp dependency
      run: |
        cd $HOME
        cd libraries/yaml-cpp
        mkdir build
        cd build
        cmake -DYAML_BUILD_SHARED_LIBS=OFF .. && cmake --build . --config ${{env.BUILD_TYPE}}

    - name: Replace dependencies path on CMakeLists file
      run: |
        cd ${{github.workspace}}
        SPDLOG_HOME=$HOME/libraries/spdlog
        NLOHMANN_HOME=$HOME/libraries/json
        PUGIXML_HOME=$HOME/libraries/pugixml
        CLI11_HOME=$HOME/libraries/CLI11
        YAML_CPP_HOME=$HOME/libraries/yaml-cpp
        sed -i "s|\$ENV{SPDLOG_HOME}|${SPDLOG_HOME}|g" CMakeLists.txt
        sed -i "s|\$ENV{NLOHMANN_HOME}|${NLOHMANN_HOME}|g" CMakeLists.txt
        sed -i "s|\$ENV{PUGIXML_HOME}|${PUGIXML_HOME}|g" CMakeLists.txt
        sed -i "s|\$ENV{CLI11_HOME}|${CLI11_HOME}|g" CMakeLists.txt
        sed -i "s|\$ENV{YAML_CPP_HOME}|${YAML_CPP_HOME}|g" CMakeLists.txt

    - name: Build
      run: |
        cd ${{github.workspace}}
        mkdir build
        cd build
        cmake .. && cmake --build . --config ${{env.BUILD_TYPE}}
        mv fastin fastin-${{env.FASTIN_VERSION}}

    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: fastin-${{env.FASTIN_VERSION}}
        path: ${{github.workspace}}/build/fastin-${{env.FASTIN_VERSION}}
        retention-days: 1

  create-tag:
    needs: [verify-version, build]
    permissions:
      contents: write
    env:
      FASTIN_VERSION: ${{ needs.verify-version.outputs.FASTIN_VERSION }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create tag
        run: |
          git tag --create ${{env.FASTIN_VERSION}}-linux
          git push origin tag ${{env.FASTIN_VERSION}}-linux
  
  create-release:
    needs: [verify-version, build, create-tag]
    permissions:
      contents: write
    env:
      FASTIN_VERSION: ${{ needs.verify-version.outputs.FASTIN_VERSION }}
    runs-on: ubuntu-latest
    steps:
      - name: Download release build artifact
        uses: actions/download-artifact@v4
        with:
          name: fastin-${{env.FASTIN_VERSION}}
          path: ${{github.workspace}}
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: create_release
        with:
          tag_name: ${{env.FASTIN_VERSION}}-linux
          release_name: Release ${{env.FASTIN_VERSION}}-linux
          draft: false
          prerelease: false
      - name: Upload release build
        uses: actions/upload-release-asset@v1
        id: upload_release_build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: ${{github.workspace}}/fastin-${{env.FASTIN_VERSION}}
          asset_name: fastin-${{env.FASTIN_VERSION}}-linux
          asset_content_type: application/octet-stream
