name: CMake on a single platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:    
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get Dependencies
      run: |
        cd $HOME
        mkdir libraries
        cd libraries
        git clone --branch=v1.x https://github.com/gabime/spdlog.git
        git clone --branch=master https://github.com/zeux/pugixml.git
        git clone --branch=master https://github.com/nlohmann/json.git
        git clone --branch=main https://github.com/CLIUtils/CLI11.git

    - name: Build spdlog dependency
      run: |
        cd $HOME
        cd libraries/spdlog
        mkdir build
        cd build
        cmake .. && cmake --build . --config ${{env.BUILD_TYPE}}
        cd ../../

    - name: Build pugixml dependency
      run: |
        cd $HOME
        cd libraries/pugixml
        mkdir build
        cd build
        cmake .. && cmake --build . --config ${{env.BUILD_TYPE}}

    - name: Add dependencies on path
      run: |
        cd $HOME
        SPDLOG_HOME="export SPDLOG_HOME=\"$HOME/libraries/spdlog\""
        NLOHMANN_HOME="export NLOHMANN_HOME=\"$HOME/libraries/json\""
        PUGIXML_HOME="export PUGIXML_HOME=\"$HOME/libraries/pugixml\""
        CLI11_HOME="export CLI11_HOME=\"$HOME/libraries/CLI11\""
        echo $SPDLOG_HOME >> .bashrc
        echo $NLOHMANN_HOME >> .bashrc
        echo $PUGIXML_HOME >> .bashrc
        echo $CLI11_HOME >> .bashrc
        cat .bashrc

    - name: Build
      run: |
        cd ${{github.workspace}}
        mkdir build
        cd build
        cmake .. && cmake --build . --config ${{env.BUILD_TYPE}}
